### ISSUE TITLE
The extension no longer works on Firefox mobile v79

### ISSUE THREAD

**Issue by fablarosa** [wisniewskit/google-search-fixer#10]
As of today this extension has been disabled on Android devices after the upgrade to Firefox 79.
Cannot test on Apple iOS.

**Comment by tgrimminger** [comment]
I've got the same problem on android and I will test it on ios later.

**Comment by Rob--W** [comment]
This will be fixed in Firefox 82. The current [Firefox Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) already supports the add-on.

PS. iOS doesn't allow browsers with extensions, so Firefox for iOS doesn't support the extension.

**Comment by ronlut** [comment]
@Rob--W Unfortunately unavailable for me in Firefox for Android Beta 82.0.0-beta6 as well.

**Comment by Rob--W** [comment]
@ronlut Did you scroll down in the Add-ons Manager? I am definitely seeing it, in 82.0.0-beta.6 (and also before, when I tested in 82.0.0-beta.2).

**Comment by ronlut** [comment]
@Rob--W you are right. It shows in the adds on manager recommended section, but not through the website, using the correct link AFAIK: https://addons.mozilla.org/en-US/android/addon/google-search-fixer/

**Comment by Rob--W** [comment]
Thanks @ronlut for reporting this issue. I am going to fix that in #959 .

**Comment by Darkmagister** [comment]
I'm trying with the android link but in version 85.0.0-beta.5 it's not available
![Screenshot_2021-01-09-01-05-34-607_org mozilla firefox_beta](https://user-images.githubusercontent.com/405742/104076698-209fc880-5217-11eb-8328-1dc6c7d715cf.jpg)

**Comment by Rob--W** [comment]
@Darkmagister Use the Add-ons manager instead of the website. It is not yet possible to install add-ons via the website.

**Comment by Darkmagister** [comment]
ok, i didn't understand that, i can find it on the addon manager thanks
